name: CI/CD

on:
  push:
    branches:
      - master
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v4
      - name: setup node 
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Generate Deployment Package 
        run: zip -r DevopsProject.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: 'DevopsProject'
          environment_name: 'DevopsProject-env'
          version_label: ${{ github.sha }}
          region: ap-south-1
          deployment_package: DevopsProject-env.zip
        env:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
